In [ ]:
!pip install torch==1.11.0 torchvision==0.12.0 torchtext==0.12.0 torchmetrics==0.7.3

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip uninstall torch torchvision torchtext torchmetrics -y

Found existing installation: torch 2.0.0+cu118
Uninstalling torch-2.0.0+cu118:
  Successfully uninstalled torch-2.0.0+cu118
Found existing installation: torchvision 0.15.1+cu118
Uninstalling torchvision-0.15.1+cu118:
  Successfully uninstalled torchvision-0.15.1+cu118
Found existing installation: torchtext 0.15.1
Uninstalling torchtext-0.15.1:
  Successfully uninstalled torchtext-0.15.1
Found existing installation: torchmetrics 0.7.3
Uninstalling torchmetrics-0.7.3:
  Successfully uninstalled torchmetrics-0.7.3


In [ ]:
! pip install pytorch-lightning~=1.5.0
! pip install datasets~=2.1.0
! pip install transformers
! pip install git+https://github.com/huggingface/accelerate
! pip install torchmetrics~=0.7.0
! pip install evaluate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.7/527.7 kB 11.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 519.2/519.2 kB 20.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 952.4/952.4 kB 35.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 17.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 114.5/114.5 kB 1.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 268.8/268.8 kB 5.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 149.6/149.6 kB 3.1 MB/s eta 0:00:00
  Attempting uninstall: setuptools
    Found existing installation: setuptools 67.7.2
    Uninstalling setuptools-67.7.2:
      Successfully uninstalled setuptools-67.7.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency c

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 325.4/325.4 kB 15.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 110.5/110.5 kB 13.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 212.5/212.5 kB 16.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.3/134.3 kB 17.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.5/224.5 kB 26.5 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.0/7.0 MB 85.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.8/7.8 MB 118.2 MB/s eta 0:00:00
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Cloning https://github.com/huggingface/accelerate to /tmp/pip-req-build-2tm0hi7l
  Running command git clone --filter=blob:none --quiet h

In [ ]:
from transformers import AutoTokenizer, AutoModel, pipeline
from datasets import load_dataset
from datasets import load_metric
import torch
import torch.nn as nn
from transformers import RobertaTokenizerFast,RobertaForSequenceClassification, AdamW, TrainingArguments, Trainer,AutoModelForSequenceClassification
dataset = load_dataset("McGill-NLP/FaithDial")


Extracting data files:   0%|          | 0/7 [00:00<?, ?it/s]

Generating test split:   0%|          | 0/3539 [00:00<?, ? examples/s]

Generating test_random_split split:   0%|          | 0/1716 [00:00<?, ? examples/s]

Generating test_topic_split split:   0%|          | 0/1823 [00:00<?, ? examples/s]

Generating train split:   0%|          | 0/18357 [00:00<?, ? examples/s]

Generating validation split:   0%|          | 0/3417 [00:00<?, ? examples/s]

Generating valid_random_split split:   0%|          | 0/1666 [00:00<?, ? examples/s]

Generating valid_topic_split split:   0%|          | 0/1751 [00:00<?, ? examples/s]

Dataset faith_dial_dataset downloaded and prepared to /root/.cache/huggingface/datasets/McGill-NLP___faith_dial_dataset/plain_text/1.0.0/70568c8ab3bbc83b603bce58fa593ab27e7f0d0cde51034e1c2073ff3e14189a. Subsequent calls will reuse this data.


  0%|          | 0/7 [00:00<?, ?it/s]

In [ ]:
dataset = load_dataset("McGill-NLP/FaithDial")

  0%|          | 0/7 [00:00<?, ?it/s]

In [ ]:
updated_dataset = dataset.map(lambda examples: {"tag": "Entailment"  if (examples["original_response"] is None and "Hallucination" not in examples["BEGIN"]) else "Hallucination"})

  0%|          | 0/3539 [00:00<?, ?ex/s]

  0%|          | 0/1716 [00:00<?, ?ex/s]

  0%|          | 0/1823 [00:00<?, ?ex/s]

  0%|          | 0/18357 [00:00<?, ?ex/s]

  0%|          | 0/3417 [00:00<?, ?ex/s]

  0%|          | 0/1666 [00:00<?, ?ex/s]

  0%|          | 0/1751 [00:00<?, ?ex/s]

In [ ]:
ud = updated_dataset.map(lambda examples: {"original_response": examples["response"]  if examples["original_response"] == None else examples["original_response"]})


  0%|          | 0/3539 [00:00<?, ?ex/s]

  0%|          | 0/1716 [00:00<?, ?ex/s]

  0%|          | 0/1823 [00:00<?, ?ex/s]

  0%|          | 0/18357 [00:00<?, ?ex/s]

  0%|          | 0/3417 [00:00<?, ?ex/s]

  0%|          | 0/1666 [00:00<?, ?ex/s]

  0%|          | 0/1751 [00:00<?, ?ex/s]

In [ ]:
sample = ud
sample

DatasetDict({
    test: Dataset({
        features: ['dialog_idx', 'response', 'original_response', 'history', 'knowledge', 'BEGIN', 'VRM', 'tag'],
        num_rows: 3539
    })
    test_random_split: Dataset({
        features: ['dialog_idx', 'response', 'original_response', 'history', 'knowledge', 'BEGIN', 'VRM', 'tag'],
        num_rows: 1716
    })
    test_topic_split: Dataset({
        features: ['dialog_idx', 'response', 'original_response', 'history', 'knowledge', 'BEGIN', 'VRM', 'tag'],
        num_rows: 1823
    })
    train: Dataset({
        features: ['dialog_idx', 'response', 'original_response', 'history', 'knowledge', 'BEGIN', 'VRM', 'tag'],
        num_rows: 18357
    })
    validation: Dataset({
        features: ['dialog_idx', 'response', 'original_response', 'history', 'knowledge', 'BEGIN', 'VRM', 'tag'],
        num_rows: 3417
    })
    valid_random_split: Dataset({
        features: ['dialog_idx', 'response', 'original_response', 'history', 'knowledge', 'BEGIN', 

In [ ]:
sample_dataset = sample.map(lambda examples: {"tag": "Entailment"})

  0%|          | 0/3539 [00:00<?, ?ex/s]

  0%|          | 0/1716 [00:00<?, ?ex/s]

  0%|          | 0/1823 [00:00<?, ?ex/s]

  0%|          | 0/18357 [00:00<?, ?ex/s]

  0%|          | 0/3417 [00:00<?, ?ex/s]

  0%|          | 0/1666 [00:00<?, ?ex/s]

  0%|          | 0/1751 [00:00<?, ?ex/s]

In [ ]:
sd = sample_dataset.map(lambda examples: {"original_response": examples["response"]})


  0%|          | 0/3539 [00:00<?, ?ex/s]

  0%|          | 0/1716 [00:00<?, ?ex/s]

  0%|          | 0/1823 [00:00<?, ?ex/s]

  0%|          | 0/18357 [00:00<?, ?ex/s]

  0%|          | 0/3417 [00:00<?, ?ex/s]

  0%|          | 0/1666 [00:00<?, ?ex/s]

  0%|          | 0/1751 [00:00<?, ?ex/s]

In [ ]:
from datasets import concatenate_datasets
# assert ud["train"].features.type == sd["train"].features.type

from datasets.dataset_dict import DatasetDict
overall = DatasetDict()

overall["train"] = concatenate_datasets([sd["train"],ud["train"]])
overall["test"] = concatenate_datasets([sd["test"],ud["test"]])
overall["validation"] = concatenate_datasets([sd["validation"],ud["validation"]])


In [ ]:
overall2 = overall.map(lambda data:{"history":""+(data["knowledge"]) if data["history"] is None else data["history"][-1]+"</s>"+data["knowledge"]})


  0%|          | 0/36714 [00:00<?, ?ex/s]

  0%|          | 0/7078 [00:00<?, ?ex/s]

  0%|          | 0/6834 [00:00<?, ?ex/s]

In [ ]:

tokenizer = RobertaTokenizerFast.from_pretrained('roberta-base', max_length = 1024)


In [ ]:
def preprocess_function(examples):
    encoding=tokenizer(examples["history"], examples["original_response"], truncation=True)
    lable= 1 if examples['tag'] == "Hallucination" else 0
    encoding["labels"]=lable
    
    return encoding
encoded_dataset = overall2.map(preprocess_function,remove_columns=ud['train'].column_names)

  0%|          | 0/36714 [00:00<?, ?ex/s]

  0%|          | 0/7078 [00:00<?, ?ex/s]

  0%|          | 0/6834 [00:00<?, ?ex/s]

In [ ]:
id2label = { 1: 'Hallucination', 0: 'Entailment'}
label2id = {'Hallucination': 1, 'Entailment': 0}

In [ ]:
model = RobertaForSequenceClassification.from_pretrained('roberta-base', num_labels=len(label2id),label2id=label2id,id2label=id2label)


# print(model)

Some weights of the model checkpoint at roberta-base were not used when initializing RobertaForSequenceClassification: ['lm_head.dense.weight', 'roberta.pooler.dense.weight', 'lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.decoder.weight', 'lm_head.layer_norm.bias', 'roberta.pooler.dense.bias', 'lm_head.dense.bias']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.weight', 'classifie

In [ ]:
import evaluate
import numpy as np
def compute_metrics(eval_preds):
    counter_one=0
    counter_zero=0
    metric = evaluate.load("glue", "mrpc")
    logits, labels = eval_preds
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [ ]:
encoded_dataset

DatasetDict({
    train: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 36714
    })
    test: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 7078
    })
    validation: Dataset({
        features: ['input_ids', 'attention_mask', 'labels'],
        num_rows: 6834
    })
})

In [ ]:
from torch import nn
from transformers import Trainer

class CustomTrainer(Trainer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    def compute_loss(self, model, inputs, return_outputs=False):
        labels = inputs.get("labels")
        # forward pass
        outputs = model(**inputs)
        logits = outputs.get("logits")

        loss_fct = nn.CrossEntropyLoss(weight=torch.tensor([4.0, 1.0]).to('cuda'))
        loss = loss_fct(logits.view(-1, self.model.config.num_labels), labels.view(-1))
        return (loss, outputs) if return_outputs else loss

In [ ]:

training_args = TrainingArguments(
    output_dir='./results',
    num_train_epochs=3,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    weight_decay=0.01,
    adafactor= False,
adam_epsilon= 1.0e-08,
    logging_dir='./logs',
    evaluation_strategy='steps',
    save_total_limit=1,
)

trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=encoded_dataset['train'],
    eval_dataset=encoded_dataset['validation'],
    tokenizer=tokenizer,
    compute_metrics=compute_metrics,
)

# # Fine-tune the model
trainer.train()

# # Evaluate the model on the test set
results = trainer.evaluate(encoded_dataset['test'])
print(results)

In [ ]:
results_pred = trainer.predict(encoded_dataset["test"])


0 3539 3539
615 2924 3539


In [ ]:
len(encoded_dataset_test)

3539

In [ ]:
len(results_pred.predictions)

3539

In [ ]:
logits = results_pred.predictions


In [ ]:
import tensorflow as tf

In [ ]:
logits

array([[-0.02095585, -0.02060651],
       [-0.02095586, -0.02060651],
       [-0.02095585, -0.0206065 ],
       ...,
       [-0.02095581, -0.02060646],
       [-0.02095579, -0.02060643],
       [-0.02095573, -0.02060638]], dtype=float32)

In [ ]:
transformed = tf.nn.softmax(logits)

In [ ]:
transformed[:15]

<tf.Tensor: shape=(15, 2), dtype=float32, numpy=
array([[0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ],
       [0.49991265, 0.5000873 ]], dtype=float32)>

In [ ]:
ground_truth = (encoded_dataset["test"]['labels'])

In [ ]:
transformed_labels = np.argmax(transformed, axis=1)

In [ ]:
# Load f1 metric
metric_f1 = evaluate.load("f1")

# Compute f1 metric
f1 = metric_f1.compute(predictions=transformed_labels, references=ground_truth)

# # Load recall metric
metric_recall = evaluate.load("recall")


metric_accuracy = evaluate.load("accuracy")
accu = metric_accuracy.compute(predictions=transformed_labels, references=ground_truth)
